# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('min_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('poi_count', models.IntegerField(default=0)),
                ('last_updated_at', models.DateTimeField()),
            ],
        ),
    ]
