# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_checkin', '0004_auto_20170309_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitaskofworker',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='poitaskofworker',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
