# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_checkin', '0005_auto_20170309_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitask',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='poitask',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
