# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_checkin', '0007_auto_20170309_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='POITaskWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.IntegerField(default=0)),
                ('min_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('min_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('poi_incr_count', models.IntegerField(default=0)),
                ('poi_repeat_count', models.IntegerField(default=0)),
                ('poi_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='poitaskofworker',
            name='task',
        ),
        migrations.AddField(
            model_name='poitask',
            name='last_error',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='poitask',
            name='poi_add_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='POITaskOfWorker',
        ),
        migrations.AddField(
            model_name='poitaskworker',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo_checkin.POITask'),
        ),
    ]
