# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_checkin', '0009_auto_20170320_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('poiid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=10)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('icon', models.CharField(max_length=200)),
                ('poi_pic', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo_checkin.Area')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo_checkin.POITask')),
            ],
        ),
    ]
