# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_checkin', '0010_poi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitask',
            name='poi_count',
        ),
        migrations.AlterField(
            model_name='poi',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weibo_checkin.Area'),
        ),
    ]
