# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_checkin', '0011_auto_20170321_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='checkin_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poi',
            name='checkin_user_num',
            field=models.IntegerField(default=0),
        ),
    ]
